crud/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.StudentListView.as_view(), name='list'),
    path('add/', views.StudentCreateView.as_view(), name='add'),
    path('update/<int:pk>', views.StudentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.StudentDeleteView.as_view(), name='delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud.urls')),
    path('crud/', include('crud.urls')),
]

crud/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Student(models.Model):
    roll = models.IntegerField(blank=True)
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    phone = models.CharField(max_length=13)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("list")
    

crud/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import Student
from django.views.generic import (CreateView, ListView,
                                    UpdateView, DeleteView)

# Create your views here.

class StudentListView(ListView):
    model = Student
    template_name = 'index.html'

class StudentCreateView(CreateView):
    model = Student
    fields = '__all__'

class StudentUpdateView(UpdateView):
    model = Student
    fields = '__all__'

class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('list')

crud/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    {% block title %} {% endblock %}
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top navbar-inverse" >
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="nav-brand" href="{% url  'list' %}">Home</a></li>
                <li title="Add a new student"><a class="nav-link" href="{% url 'add' %}">Add Student</a></li>
                <li title="Go to admin interface"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            </ul>
        </div>  
    </nav>
    
    <div class="container">
        {% block body %}

        {% endblock %}
    </div>
        
</body>
</html>

crud/templates/crud/student_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Confirm Delete</title>
{% endblock %}

{% block body %}
    <div class="jumbotron">
    <h2>Are you sure?</h2>
    <p>you want to delete: {{student.name}}</p>
    <form method="POST">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Delete">
        <a class="btn btn-info" href="{% url 'list' %}">Cancel</a>
        
    </form>
    </div>
    
{% endblock %}

crud/templates/crud/student_form.html
{% extends 'base.html' %}

{% block title %}
    <title>
        {% if not form.instance.pk %}
        Add Student
        {% else %}
        Update Student
        {% endif %}
    </title>   
 {% endblock %}

{% block body %}
    <div class="jumbotron">
        <!-- <h2>Add Student Details here...</h2> -->
        <h2>
            {% if not form.instance.pk %}
            Add Student Details.
            {% else %}
            Update Student Details.
            {% endif %}
        </h2>
        <br/>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

crud/templates/index.html
{% extends 'base.html' %}

{% block title %}
    <title>Home Page</title>
{% endblock %}

{% block body %}
<table class="table">
    <thead>
      <tr>
        <th>Roll NO.</th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
        {% for student in student_list %}
        <tr class="success">
            <td>{{student.roll}}</td>
            <td>{{student.name}}</td>
            <td>{{student.email}}</td>
            <td>{{student.phone}}</td>
            <td>
                <a class="btn btn-info" href="{% url 'update' student.id %}">Update</a>
                <a class="btn btn-warning" href="{% url 'delete' student.id %}">Delete</a>
            </td>
        </tr>
        {% endfor %}
      
    </tbody>
  </table>
{% endblock %}